name: Push to master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      version: ${{ steps.cz.outputs.version }}
      changed: ${{ steps.version-changed.outputs.changed }}

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - id: version-changed
        name: Check if version changed
        run: |
          [[ $REVISION = $PREVIOUS_REVISION ]] && CHANGED="false" || CHANGED="true"
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
          [[ $CHANGED = "true" ]] && echo "::notice::Version changed ($PREVIOUS_REVISION -> $REVISION)" || echo "::notice::Version did not change"

  create-release:
    needs: bump-version
    runs-on: ubuntu-latest
    name: "Create release"
    outputs:
      release_id: ${{ steps.release.outputs.id }}
      release_url: ${{ steps.release.outputs.url }}
      release_upload_url: ${{ steps.release.outputs.upload_url }}
    if: "${{ needs.bump-version.outputs.changed == 'true' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_name: v${{ needs.bump-version.outputs.version }}

      - name: Echo release id
        run: echo "::notice::id=${{ steps.release.outputs.id }}"

  publish-olve-utilities:
    needs:
      - bump-version
    runs-on: ubuntu-latest
    name: "Publish Olve.Utilities"
    if: "${{ needs.bump-version.outputs.changed == 'true' }}"
    steps:
    - uses: actions/checkout@v4

    - name: Publish Olve.Utilities to NuGet
      uses: ./.github/actions/dotnet-publish
      with:
        project: ./src/Olve.Utilities
        package-name: Olve.Utilities
        version: ${{ needs.bump-version.outputs.version }}
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        dry-run: true