name: Push to master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "${{ startsWith(github.event.head_commit.message, 'bump:') != 'true' }}"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  publish-olve-utilities:
    needs: bump-version
    runs-on: ubuntu-latest
    name: "Publish Olve.Utilities"
    steps:
    - uses: actions/checkout@v4

    - name: Publish Olve.Utilities to NuGet
      uses: ./.github/actions/dotnet-publish
      with:
        project: ./src/Olve.Olve.Utilities
        package-name: Olve.Utilities
        version: ${{ needs.bump-version.outputs.version }}
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        dry-run: true